# Generated by Django 5.2 on 2025-05-07 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSheet',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='タイトル')),
                ('guest_comapny_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='お客様社名')),
                ('answered_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='記入者')),
                ('answered_at', models.DateField(blank=True, null=True, verbose_name='記入日')),
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_check_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_or_ip_address', models.CharField(max_length=200, null=True, verbose_name='診断対象のURLまたはIPアドレス')),
                ('host_name', models.CharField(max_length=200, null=True, verbose_name='ホスト名')),
                ('os', models.CharField(max_length=200, null=True, verbose_name='OS')),
                ('web_server', models.CharField(max_length=200, null=True, verbose_name='Webサーバ')),
                ('ap_server', models.CharField(max_length=200, null=True, verbose_name='APサーバ')),
                ('framework', models.CharField(max_length=200, null=True, verbose_name='フレームワーク')),
                ('db_server', models.CharField(max_length=200, null=True, verbose_name='DBサーバ')),
                ('check_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assess_targets', to='check_sheet.checksheet')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=200, null=True, verbose_name='システム正式名称')),
                ('system_abbr_name', models.CharField(max_length=200, null=True, verbose_name='システム略称')),
                ('system_overview', models.TextField(null=True, verbose_name='システムの利用目的')),
                ('environment', models.CharField(blank=True, choices=[('production', '本番環境'), ('development', '開発環境'), ('maintenance', '保守環境'), ('other', 'その他')], max_length=20, null=True, verbose_name='診断実施環境')),
                ('environment_other', models.CharField(blank=True, max_length=200, null=True, verbose_name='')),
                ('dev_lang', models.TextField(null=True, verbose_name='開発言語')),
                ('is_released', models.BooleanField(default=False, null=True, verbose_name='リリース済')),
                ('release_date', models.DateField(null=True, verbose_name='リリース日')),
                ('check_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='check_sheet.checksheet')),
            ],
        ),
    ]
