# Generated by Django 5.2 on 2025-05-02 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSheet',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_q1', models.CharField(choices=[('inhouse', '自社管理'), ('hosting', '外部委託(ホスティング)'), ('cloud', '外部委託(クラウド)')], max_length=50, verbose_name='Q1. 運営組織')),
                ('hearing_q2_1', models.CharField(blank=True, max_length=200, verbose_name='Q2-1. 委託先')),
                ('hearing_q2_2', models.CharField(blank=True, choices=[('none', '不要'), ('done', '済み'), ('undone', '未申請')], max_length=20, verbose_name='Q2-2. 事前申請')),
                ('hearing_q3', models.BooleanField(default=False, verbose_name='Q3. 外部公開ポート有無')),
                ('hearing_q4', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, verbose_name='Q4. SSL/TLS 利用有無')),
                ('hearing_q5', models.CharField(blank=True, max_length=50, verbose_name='Q5. 認証方式')),
                ('hearing_q6', models.TextField(blank=True, verbose_name='Q6. セッション管理方法')),
                ('hearing_q7', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, verbose_name='Q7. ファイルアップロード機能有無')),
                ('hearing_q8', models.CharField(blank=True, max_length=200, verbose_name='Q8. アップロード制限（拡張子/サイズ）')),
                ('hearing_q9', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, verbose_name='Q9. 管理者機能有無')),
                ('hearing_q10', models.TextField(blank=True, verbose_name='Q10. 管理者機能詳細')),
                ('hearing_q11', models.BooleanField(default=False, verbose_name='Q11. Web API 提供有無')),
                ('hearing_q12', models.TextField(blank=True, verbose_name='Q12. Web API 認証方式')),
                ('hearing_q13', models.BooleanField(default=False, verbose_name='Q13. メール送信機能有無')),
                ('hearing_q14', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, verbose_name='Q14. CAPTCHA 利用有無')),
                ('hearing_q15', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, verbose_name='Q15. パスワード再発行機能有無')),
                ('hearing_q16', models.TextField(blank=True, verbose_name='Q16. パスワードポリシー')),
                ('hearing_q17', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, verbose_name='Q17. 外部連携サービス有無')),
                ('hearing_q18', models.TextField(blank=True, verbose_name='Q18. 外部連携サービス詳細')),
                ('hearing_q19', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, verbose_name='Q19. 多要素認証有無')),
                ('hearing_q20', models.TextField(blank=True, verbose_name='Q20. レート制限（API 等）')),
                ('hearing_q21', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, verbose_name='Q21. CSRF 対策有無')),
                ('hearing_q22', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, verbose_name='Q22. XSS 対策有無')),
                ('hearing_q23', models.TextField(blank=True, verbose_name='Q23. その他特記すべきセキュリティ要件')),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hearing', to='check_sheet.checksheet')),
            ],
        ),
        migrations.CreateModel(
            name='LoginCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(verbose_name='No')),
                ('login_id', models.CharField(blank=True, max_length=200, verbose_name='ログイン ID')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='パスワード')),
                ('privilege', models.CharField(blank=True, max_length=200, verbose_name='権限')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='check_sheet.checksheet')),
            ],
            options={
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_checks', models.TextField(blank=True, verbose_name='事前チェック／注意事項')),
                ('onsite_info', models.TextField(blank=True, verbose_name='オンサイト情報')),
                ('network_info', models.TextField(blank=True, verbose_name='ネットワーク情報')),
                ('others', models.TextField(blank=True, verbose_name='その他')),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='check_sheet.checksheet')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='宛先氏名／部署')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='会社名')),
                ('email', models.EmailField(max_length=254, verbose_name='メール')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='郵送先住所')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_recipients', to='check_sheet.checksheet')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('extension_allowed', models.BooleanField(default=False, verbose_name='延長可否')),
                ('extension_contact_required', models.BooleanField(default=False, verbose_name='延長時連絡要否')),
                ('extension_action', models.CharField(choices=[('continue', '続行'), ('stop', '中止')], max_length=10, verbose_name='連絡不通時の対応')),
                ('backup_date', models.DateField(blank=True, null=True, verbose_name='予備日')),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='check_sheet.checksheet')),
            ],
        ),
        migrations.CreateModel(
            name='TargetURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(verbose_name='No')),
                ('url', models.URLField(verbose_name='URL または IP')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='ホスト名')),
                ('os', models.CharField(blank=True, max_length=200, verbose_name='OS')),
                ('web_server', models.CharField(blank=True, max_length=200, verbose_name='Web サーバ')),
                ('app_server', models.CharField(blank=True, max_length=200, verbose_name='AP サーバ')),
                ('framework', models.CharField(blank=True, max_length=200, verbose_name='フレームワーク')),
                ('db_server', models.CharField(blank=True, max_length=200, verbose_name='DB サーバ')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_urls', to='check_sheet.checksheet')),
            ],
            options={
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'お客様'), ('related', '関係会社')], max_length=10, verbose_name='役割')),
                ('company', models.CharField(max_length=200, verbose_name='会社名')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('department', models.CharField(max_length=200, verbose_name='部署')),
                ('contact1', models.CharField(max_length=50, verbose_name='連絡先①')),
                ('contact2', models.CharField(blank=True, max_length=50, verbose_name='連絡先②')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='check_sheet.checksheet')),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium')], max_length=10, verbose_name='通知レベル')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('affiliation', models.CharField(blank=True, max_length=200, verbose_name='所属')),
                ('phone', models.CharField(max_length=50, verbose_name='電話番号')),
                ('email', models.EmailField(max_length=254, verbose_name='メール')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_contacts', to='check_sheet.checksheet')),
            ],
        ),
    ]
