# Generated by Django 5.2 on 2025-05-08 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsummary',
            name='check_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_sheet.checksheet'),
        ),
        migrations.CreateModel(
            name='LoginCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=255, verbose_name='ログインID')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('role', models.CharField(max_length=255, verbose_name='権限')),
                ('check_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_credentials', to='check_sheet.checksheet')),
            ],
        ),
    ]
