# Generated by Django 5.2 on 2025-05-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_sheet', '0002_alter_systemsummary_check_sheet_logincredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address_management', models.CharField(choices=[('自社管理', '自社管理'), ('外部委託 (ホスティング)', '外部委託 (ホスティング)'), ('外部委託 (クラウドサービス)', '外部委託 (クラウドサービス)')], max_length=200, null=True, verbose_name='診断対象IPアドレスの運営組織について該当する物を選択してください。')),
                ('outsourcing_info', models.CharField(max_length=200, null=True, verbose_name='前項Q1で「外部委託 (ホスティング)」または「外部委託 (クラウドサービス)」を回答された場合は、以下の事項にもご回答ください。外部委託先の情報をご回答ください。')),
                ('pre_application_required', models.BooleanField(null=True, verbose_name='利用している委託先によっては、セキュリティ診断の際に事前申請が必要な場合があります。事前申請が必要か、また既に申請が完了しているかご回答ください。')),
                ('pre_application_status', models.CharField(choices=[('申請済み', '申請済み'), ('未申請', '未申請')], max_length=200, null=True, verbose_name='事前申請が必要か、また既に申請が完了しているかご回答ください。')),
                ('check_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_questions', to='check_sheet.checksheet')),
            ],
        ),
    ]
