# Generated by Django 5.2 on 2025-05-09 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_sheet', '0003_requiredquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredquestion',
            name='outsourcing_info',
            field=models.CharField(max_length=200, null=True, verbose_name='委託先'),
        ),
        migrations.AlterField(
            model_name='requiredquestion',
            name='pre_application_required',
            field=models.BooleanField(null=True, verbose_name='利用している委託先によっては、セキュリティ診断の際に事前申請が必要な場合があります。事前申請が必要ですか。'),
        ),
        migrations.AlterField(
            model_name='requiredquestion',
            name='pre_application_status',
            field=models.CharField(choices=[('申請済み', '申請済み'), ('未申請', '未申請')], max_length=200, null=True, verbose_name='申請済みですか。'),
        ),
        migrations.CreateModel(
            name='PreparedDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_management_design', models.BooleanField(default=False, verbose_name='セッション管理に関する基本設計書 (または事前ヒアリング)')),
                ('authentication_design', models.BooleanField(default=False, verbose_name='認証 (ログイン) に関する基本設計書 (または事前ヒアリング)')),
                ('target_screen_list', models.BooleanField(default=False, verbose_name='診断対象画面一覧')),
                ('screen_transition_diagram', models.BooleanField(default=False, verbose_name='画面遷移図')),
                ('network_configuration_diagram', models.BooleanField(default=False, verbose_name='ネットワーク構成図')),
                ('web_server_directory_list', models.BooleanField(default=False, verbose_name='Webサーバの公開ディレクトリおよびファイル一覧')),
                ('check_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_docs', to='check_sheet.checksheet')),
            ],
        ),
    ]
