# Generated by Django 5.2 on 2025-05-09 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_sheet', '0004_alter_requiredquestion_outsourcing_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True, verbose_name='実施日付（開始）')),
                ('end_date', models.DateField(null=True, verbose_name='実施日付（終了）')),
                ('start_time', models.TimeField(null=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(null=True, verbose_name='終了時刻')),
                ('extension_possible', models.BooleanField(null=True, verbose_name='延長可否')),
                ('extension_contact', models.BooleanField(max_length=200, null=True, verbose_name='連絡要否')),
                ('extension_continue', models.BooleanField(null=True, verbose_name='連絡不通時の続行')),
                ('backup_date', models.DateField(null=True, verbose_name='予備日')),
                ('check_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedules', to='check_sheet.checksheet')),
            ],
        ),
    ]
