# Generated by Django 5.2 on 2025-05-09 05:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_sheet', '0005_assessschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessschedule',
            name='extension_contact',
            field=models.BooleanField(null=True, verbose_name='連絡要否'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True, verbose_name='会社')),
                ('member_name', models.CharField(max_length=200, null=True, verbose_name='氏名')),
                ('department_name', models.CharField(max_length=200, null=True, verbose_name='部署名')),
                ('phone_number_1', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_2', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('check_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='check_sheet.checksheet')),
            ],
        ),
    ]
