# Generated by Django 5.2 on 2025-05-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_sheet', '0006_alter_assessschedule_extension_contact_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number_1',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
